regions:
- name: solderPotReal
  left: 106
  top: 245
  width: 104
  height: 23
- name: preHeat1BSet
  left: 106
  top: 245
  width: 104
  height: 23
- name: preHeat1BReal
  left: 367
  top: 180
  width: 559
  height: 169
- name: preHeat2BSet
  left: 88
  top: 425
  width: 172
  height: 20
- name: preHeat2BReal
  left: 89
  top: 387
  width: 76
  height: 21
- name: preHeat3BSet
  left: 88
  top: 425
  width: 172
  height: 20
- name: preHeat3BReal
  left: 89
  top: 387
  width: 76
  height: 21
- name: GuideWidth
  left: 89
  top: 387
  width: 76
  height: 21
- name: crest1
  left: 89
  top: 387
  width: 76
  height: 21
- name: crest2
  left: 89
  top: 387
  width: 76
  height: 21
- name: Capacity
  left: 89
  top: 387
  width: 76
  height: 21
- name: preHeatFan
  left: 89
  top: 387
  width: 76
  height: 21
ocr_url: http://127.0.0.1:1224/api/ocr
show_log: false
buttons:
- name: '1'
  left: 0
  top: 0
  width: 50
  height: 50
  on_image: D:/tpFile/备份脚本/python_code/OCR测试/screenshot.png
  off_image: D:/tpFile/备份脚本/python_code/OCR测试/screenshot.png
  threshold: 0.8
  timeout: 3
  interval: 0.1
  use_opencv: true
settings:
  auto_start_with_windows: false
